# This docker-compose file starts an entire wasmCloud ecosystem, including:
#   a NATS server
#   a local OCI registry
#   grafana + prometheus + tempo for metrics and tracing
#   a wasmCloud host
#   a WADM server for managing applications

version: "3"
services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "4223:4223"
    command:
      - "-c=/etc/nats/nats-server.conf"
    volumes:
      - ./nats.websocket.conf:/etc/nats/nats-server.conf

  wasmcloud:
    depends_on:
      - "nats"
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_ALLOW_FILE_LOAD: "true"
    ports:
      - "8000-8100:8000-8100" # Expose ports 8000-8100 for examples that use an HTTP server

  wadm:
    depends_on:
      - "nats"
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      - WADM_NATS_SERVER=nats